### ISSUE TITLE
Scroll-speed is constant in IE11

### ISSUE THREAD

**Issue by InFerYes** [padsbanger/angular-backtop#11]
I have changed the scroll-speed from 600 to 6000 or 0 (instant) but the scroll-speed is invariably 600 in IE, I'm not sure why it keeps using the default value. I have tested with others browsers and they are correctly affected by the scroll-speed value.

Issue happens with IE11 11.0.9600.18204

**Comment by padsbanger** [comment]
Sorry, I don`t have access to machine with IE at the moment, pull request is welcome :smile:
