### ISSUE TITLE
Integrate with ASP.NET MVC 5

### ISSUE THREAD

**Issue by sopheakmorm** [padsbanger/angular-backtop#12]
Hi all,
I would like to use it for my project that built in ASP.
But It not work fine.
How can I build it ?

thank

**Comment by padsbanger** [comment]
Hello,

Not sure how ASP works, but you have build library in`dist` directory. Just take `angular-backtop.min.js` and `angular-backtop.css` and include it into your project.

**Comment by sopheakmorm** [comment]
now it work fine. thank you guy
