### ISSUE TITLE
#error NPM repo has old data

### ISSUE THREAD

**Issue by WuglyakBolgoink** [padsbanger/angular-backtop#13]
if you install plugin via NPM -     `"angular-backtop": "0.0.1"`
source code has wrong template value:

```
    template: '<div id="backtop" class="{{theme}}"><button>{{text}}</button></div>',
```

please update version or code!

**Comment by padsbanger** [comment]
Hello, I don` t understand what excatly is wrong, care to explain ? Pull request is welcome.

**Comment by WuglyakBolgoink** [comment]
Hi @padsbanger 

npm-repo has old version of this component, with `<button>{{text}}</button>`, in bower repo this part was changed with ngTransclude!

do npm publish

**Comment by padsbanger** [comment]
Bumped version to `0.0.3`
