### ISSUE TITLE
angular dependencies kill my build server

### ISSUE THREAD

**Issue by WuglyakBolgoink** [padsbanger/angular-backtop#18]
Jenkins server found conflict

> bower                                                ECONFLICT Unable to find suitable version for angular

please remove this from bower config
```json
 "dependencies": {
    "angular": "~1.3.15"
},
```

**Comment by padsbanger** [comment]
How removing `angular` from bower dependencies could possibly fix it ? It will crash my builds.

**Comment by WuglyakBolgoink** [comment]
because jenkins do `bower install` and bower has conflict with versions... are we need this dependency?

tnx for fix npm-repo, now jenkins work ok ))

**Comment by padsbanger** [comment]
Moving angular to devDeps in bower.json might fix this, however I will not set up Jenkins env to test it, for obvious reason :)
